### ISSUE TITLE
Try changing this

### ISSUE THREAD

**Issue by missingno15** [chasemlim/a-A-Homework#1]
https://github.com/chasemlim/a-A-Homework/blob/7a49524b426aa7145a06bb770d5f6afd2d4feea4/W3D3_HW/W3D3/db/migrate/20181107051035_people.rb#L1

This is a wild guess for reasons I'm not quite sure of myself but try renaming this to `CreatePersonTable`. My guess is that there is some weird naming conflict going on.

**Comment by missingno15** [comment]
also rename the migration file appropriately, so `create_person_table`

**Comment by chasemlim** [comment]
Didn't work unfortunately, same error. I appreciate the help though
